# Site settings
title: Dominik Inführ
email: dominik.infuehr@gmail.com
description: "&lt;insert some cool introduction to myself here&gt;"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: dinfuehr
github_username:  dinfuehr

# Build settings
markdown: kramdown
permalink: pretty
